[platformio]
default_envs = agentdeck

[env:agentdeck]
platform = espressif32@6.12.0
board = esp32-s3-devkitc-1
framework = arduino
lib_deps =
    olikraus/U8g2@2.36.15
    knolleary/PubSubClient@2.8
    bblanchon/ArduinoJson@6.21.5
board_build.partitions = default_8MB.csv
monitor_speed = 115200
build_flags =
    -D ARDUINO_USB_CDC_ON_BOOT=0
    -D CORE_DEBUG_LEVEL=0
    -Wall
    -Wextra

[env:agentdeck-usb]
extends = env:agentdeck
build_flags =
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D CORE_DEBUG_LEVEL=0
    -Wall
    -Wextra
